nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['https://instapictures.jumperboost.fr']
        allow_methods: ['GET']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        allow_credentials: true
        max_age: 43200
    paths:
        '^/': null
